[package]
name = "superplaced-cv"
version = "0.3.0"
entrypoint = "lib.typ"
authors = ["Sina Atalay <dev@atalay.biz>"]
license = "MIT"
description = "Resume builder for academics and engineers"
repository = "https://github.com/superplaced-cv/superplaced-cv"
keywords = ["superplaced-cv", "cv", "resume", "curriculum-vitae"]
categories = ["cv"]
disciplines = []
compiler = "0.14.0"
exclude = ["examples/*.pdf"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
