import { NextResponse } from 'next/server';
import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import path from 'path';

const execAsync = promisify(exec);

export async function POST(req: Request) {
  try {
    const data = await req.json();
    
    // Create a temporary directory for the rendering process
    const tempDir = path.join(process.cwd(), 'tmp', `rendercv_${Date.now()}`);
    await fs.mkdir(tempDir, { recursive: true });
    
    const expEntries = (data.experience || []).map((exp: { company: string; role: string; dates: string; description: string }) =>
      `      - company: "${exp.company}"\n        position: "${exp.role}"\n        date: "${exp.dates}"\n        highlights:\n          - "${exp.description.replace(/"/g, "'")}"`
    ).join('\n');

    const eduEntries = (data.education || []).map((edu: { school: string; degree: string; dates: string }) =>
      `      - institution: "${edu.school}"\n        area: "${edu.degree}"\n        date: "${edu.dates}"`
    ).join('\n');

    const yamlData = `cv:
  name: ${data.name || 'User'}
  location: ${data.location || ''}
  email: ${data.email || ''}
  phone: "${data.phone || ''}"
  sections:
    summary:
      - "${(data.summary || '').replace(/"/g, "'")}"
    experience:
${expEntries}
    education:
${eduEntries}
    skills:
      - label: "Core Skills"
        details: "${(data.skills || []).join(', ')}"
design:
  theme: classic
`;

    const yamlPath = path.join(tempDir, 'resume.yaml');
    await fs.writeFile(yamlPath, yamlData);
    
    console.log('Running RenderCV...');
    
    try {
      // Execute RenderCV
      await execAsync(`python -m rendercv render ${yamlPath}`, { cwd: tempDir });
      
      // Typical output is rendercv_output/User_CV.pdf
      const outputDir = path.join(tempDir, 'rendercv_output');
      const files = await fs.readdir(outputDir);
      const pdfFile = files.find(f => f.endsWith('.pdf'));
      
      if (!pdfFile) {
        throw new Error('PDF file not generated');
      }
      
      const publicPdfPath = path.join(process.cwd(), 'public', 'generated_cv.pdf');
      await fs.copyFile(path.join(outputDir, pdfFile), publicPdfPath);
      
      return NextResponse.json({ 
        success: true, 
        message: 'CV successfully generated by Superplaced AI CV Engine (Powered by RenderCV)!',
        pdfUrl: '/generated_cv.pdf' 
      });
      
    } catch (renderError: unknown) {
      const errMsg = renderError instanceof Error ? renderError.message : String(renderError);
      console.error('RenderCV Execution Error:', errMsg);
      return NextResponse.json({ 
        success: false, 
        error: 'RenderCV validation or compilation failed. Ensure your data meets the strict schema requirements.' 
      }, { status: 400 });
    }

  } catch (error) {
    console.error('Error generating CV:', error);
    return NextResponse.json({ success: false, error: 'Failed to process request' }, { status: 500 });
  }
}
